### ISSUE TITLE
[Server] ValidationError doesn't return messages

### ISSUE THREAD

**Issue by domeknn** [kareem3d/redux-typescript-nodejs#1]
`server/errors.ts`

Method getMessages()
`getMessages() {
    return this.messages;
  }`

should be

`getMessages() {
    return this.message;
  }`

anyway nice work , keep it up!

**Comment by kareemaly** [comment]
@domeknn if you look at the ValidationError constructor you will see that I have defined a private messages object so `getMessages()` returns that object which should contain validation errors for different inputs. e.g.

```
{
  "email": ["Email format is invalid"],
  "username": ["Username length must be greater than 8 characters", "Username can't start with numbers"]
}
```
